site_name: serverless-builder
site_description: Python interface to easily generate serverless.yml files
site_author: EpsyLabs engineering@epsyhealth.com
repo_url: https://github.com/epsylabs/serverless-builder

nav:
  - Start here: index.md
  - Usage: usage.md
  - Plugins: plugins.md
  - Integrations: integrations.md
  - Use with CI/CD: ci.md

theme:
  name: material
  features:
    - navigation.instant
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  palette:
    - scheme: default
      primary: 'deep purple'
      accent: 'red'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - meta
    - wikilinks
    - codehilite:
        linenums: True
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/epsylabs/serverless-builder'

copyright: Copyright EpsyHealth &copy; 2022 All rights reserved

plugins:
  - search
