site_name: serverless-builder
site_description: Python interface to easily generate serverless.yml files
site_author: EpsyLabs engineering@epsyhealth.com
repo_url: https://github.com/epsylabs/serverless-builder

nav:
  - Start here: index.md
  - Usage: usage.md
  - Plugins: plugins.md
  - Integrations: integrations.md
  - Use with CI/CD: ci.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2022 All rights reserved

plugins:
  - search
